databases:
  - name: Life-plus
    databaseName: life_plus_db
    user: Life-plus
    region: singapore

services:
  - type: web
    name: Life-plus
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Life-plus_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false